let message = "Start choose district";
document.querySelector("#glow-ingress-block").textContent;
document.querySelector("div#nav-global-location-slot a").click();
// show the old value;
document.querySelector("input#GLUXZipUpdateInput_0").value;
// enter the new value;
document.querySelector("input#GLUXZipUpdateInput_0").value = 'A1A';
document.querySelector("input#GLUXZipUpdateInput_0").value;
document.querySelector("input#GLUXZipUpdateInput_1").value = '1A1';
document.querySelector("input#GLUXZipUpdateInput_1").value;
// check if the elements are visible;
document.querySelector("input#GLUXZipUpdateInput_0").outerHTML;
document.querySelector("input#GLUXZipUpdateInput_1").outerHTML;
document.querySelector("#GLUXZipUpdate").outerHTML;
document.querySelector("input#GLUXConfirmClose").outerHTML;
document.querySelector("#GLUXZipInputSection").outerHTML;
// click apply button;
document.querySelector("#GLUXZipUpdate input").click();
message = "Confirm dialog must show";
document.querySelector("div#GLUXHiddenSuccessDialog").outerHTML;
document.querySelector("input#GLUXConfirmClose").click();
// show the new value;
message = "Show the new value";
document.querySelector("#glow-ingress-block").textContent;
// click apply
// document.querySelector("span#a-autoid-1 button").click();
// document.querySelector("button[name=glowDoneButton]").click();
// document.querySelector("#glow-ingress-block").click();
// show the new value;
message = "Show the new value again";
document.querySelector("#glow-ingress-block").textContent;
