package com.github.kklisura.cdt.protocol.v2023;

/*
 * Chrome DevTools protocol version 2023.
 *
 * <p>Generated by kklisura.
 *
 * @see <a href="https://github.com/kklisura/chrome-devtools-java-client">Chrome DevTools Java Client</a>
 * @see <a href="https://chromedevtools.github.io/devtools-protocol/tot/">Chrome DevTools Protocol</a>
 */

