/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fun.platonic.pulsar.crawl.parse;

// Hadoop imports

import fun.platonic.pulsar.common.config.ReloadableParameterized;
import fun.platonic.pulsar.crawl.protocol.Protocol;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import fun.platonic.pulsar.persist.WebPage;

/**
 * A parser for content generated by a
 * {@link Protocol} implementation. This interface is
 * implemented by extensions. PulsarConstants's core contains no page parsing code.
 */
public interface Parser extends ReloadableParameterized {

    Logger LOG = LoggerFactory.getLogger(Parser.class);

    /**
     * <p>
     * This method parses content in WebPage instance
     * </p>
     *
     * @param page
     */
    ParseResult parse(WebPage page);
}
