/**
 * Autogenerated by Avro
 *
 *
 * DO NOT EDIT DIRECTLY
 */
package ai.platon.pulsar.persist.model

import ai.platon.pulsar.persist.gora.generated.GFieldGroup

class FieldGroup private constructor(private val fieldGroup: GFieldGroup) {
    fun unbox(): GFieldGroup {
        return fieldGroup
    }

    var id: Long
        get() = fieldGroup.id
        set(id) {
            fieldGroup.id = id
        }

    var parentId: Long
        get() = fieldGroup.parentId
        set(id) {
            fieldGroup.parentId = id
        }

    var name: String
        get() = fieldGroup.name.toString()
        set(name) {
            fieldGroup.name = name
        }

    var fields: Map<String, String?>
        get() = fieldGroup.fields.entries.associate { it.key.toString() to it.value?.toString() }
        set(value) {
            fieldGroup.fields = value.entries.associate { it.key to it.value }
        }

    override fun toString(): String {
        return FieldGroupFormatter(this).format()
    }

    companion object {
        @JvmOverloads
        fun newFieldGroup(id: Long, name: String, parentId: Long = 0): FieldGroup {
            val fieldGroup = GFieldGroup.newBuilder().build()
            fieldGroup.id = id
            fieldGroup.parentId = parentId
            fieldGroup.name = name
            return box(fieldGroup)
        }

        fun box(fieldGroup: GFieldGroup): FieldGroup {
            return FieldGroup(fieldGroup)
        }
    }
}
