package ai.platon.pulsar.manual

import ai.platon.pulsar.agentic.context.AgenticContexts
import ai.platon.pulsar.common.sql.ResultSetFormatter
import ai.platon.pulsar.skeleton.PulsarSettings

/**
 * # X-SQL Reference - Query the Web with SQL Syntax
 *
 * This example demonstrates X-SQL (eXtended SQL), Browser4's unique feature
 * that allows you to query web pages using familiar SQL syntax.
 *
 * ## Key Concepts:
 * 1. **X-SQL** - SQL-like language for web data extraction
 * 2. **DOM Functions** - Built-in functions for parsing HTML
 * 3. **URL Functions** - Functions for fetching web pages
 * 4. **String Functions** - Text manipulation utilities
 *
 * ## X-SQL Architecture:
 * ```
 * SQL Query → Parser → Web Fetcher → DOM Selector → Result Set
 * ```
 *
 * ## Core Functions:
 *
 * ### URL Functions (Data Sources)
 * | Function | Description |
 * |----------|-------------|
 * | `load_and_select(url, selector)` | Load page and select root element |
 * | `load(url)` | Load page without selection |
 *
 * ### DOM Functions (Element Selection)
 * | Function | Description |
 * |----------|-------------|
 * | `dom_first_text(dom, selector)` | Get first matching element's text |
 * | `dom_all_texts(dom, selector)` | Get all matching elements' texts |
 * | `dom_first_attr(dom, selector, attr)` | Get first element's attribute |
 * | `dom_first_href(dom, selector)` | Get first link's href |
 *
 * ### String Functions (Text Processing)
 * | Function | Description |
 * |----------|-------------|
 * | `str_first_float(text, default)` | Extract first float from text |
 * | `str_first_integer(text, default)` | Extract first integer from text |
 * | `str_substring_after(text, sep)` | Get text after separator |
 *
 * ## CSS Selector Syntax in X-SQL:
 * - Standard CSS: `#id`, `.class`, `tag`
 * - Attribute: `[attr=value]`
 * - Pseudo: `:contains(text)`, `:matches(regex)`
 * - Combinators: `parent > child`, `sibling ~ sibling`
 *
 * ## Load Options in X-SQL:
 * URL supports all standard load options:
 * - `-i 1s` - Expiration interval
 * - `-njr 3` - JIT retry count (Just-In-Time retries)
 * - `-refresh` - Force re-fetch
 *
 * ## AI Integration Notes:
 * - X-SQL can be generated by AI from natural language queries
 * - AI can analyze SQL results for further insights
 * - Useful for AI-powered data extraction pipelines
 *
 * @see ResultSetFormatter Formats SQL results for display
 * @see AgenticContexts Context with AI and SQL capabilities
 */
fun main() {
    // =====================================================================
    // STEP 1: Browser Configuration
    // =====================================================================
    // Use the default browser which has an isolated profile.
    PulsarSettings.withDefaultBrowser()

    // Create an agentic context which supports X-SQL execution
    // AI Note: AgenticContexts provides both SQL execution and AI features
    val context = AgenticContexts.create()
    
    // =====================================================================
    // STEP 2: X-SQL Query Definition
    // =====================================================================
    //
    // This SQL query extracts product information from an Amazon page.
    //
    // Query Breakdown:
    // 1. FROM clause: load_and_select() fetches the page and selects 'body' as root
    // 2. SELECT clause: Extract specific fields using DOM functions
    //
    // AI Note: The load_and_select() function:
    // - First argument: URL with load options ('-i 1s -njr 3')
    // - Second argument: CSS selector for root element ('body')
    // - Returns: DOM object that can be queried with dom_* functions
    val sql = """
select
      -- Extract product title from #productTitle element
      dom_first_text(dom, '#productTitle') as title,
      
      -- Extract brand from #bylineInfo element  
      dom_first_text(dom, '#bylineInfo') as brand,
      
      -- Extract price using complex CSS selector
      -- Looks in two possible locations: #price or #corePrice_desktop
      -- Uses :matches(^Price) to find "Price" label, then ~ td to get adjacent cell
      dom_first_text(dom, '#price tr td:matches(^Price) ~ td, #corePrice_desktop tr td:matches(^Price) ~ td') as price,
      
      -- Extract review count from customer review text
      dom_first_text(dom, '#acrCustomerReviewText') as ratings,
      
      -- Extract and convert rating score to float
      -- Uses str_first_float() to parse "4.5 out of 5" → 4.5
      -- Second argument (0.0) is default if parsing fails
      str_first_float(dom_first_text(dom, '#reviewsMedley .AverageCustomerReviews span:contains(out of)'), 0.0) as score
      
  from load_and_select('https://www.amazon.com/dp/B08PP5MSVB -i 1s -njr 3', 'body');
            """
    
    // =====================================================================
    // STEP 3: Execute Query and Format Results
    // =====================================================================
    //
    // Execute the X-SQL query and get results as a standard JDBC ResultSet.
    // AI Note: ResultSet is compatible with standard Java database tools.
    val rs = context.executeQuery(sql)
    
    // Format and print the results as a table
    // AI Note: ResultSetFormatter creates readable output:
    // - withHeader=true includes column names
    // - Automatically adjusts column widths
    println(ResultSetFormatter(rs, withHeader = true))
    
    // =====================================================================
    // Additional X-SQL Examples (Reference)
    // =====================================================================
    //
    // Example 1: Extract multiple products from a listing page
    // ```sql
    // select
    //     dom_first_text(dom, '.product-title') as title,
    //     dom_first_href(dom, '.product-link') as url
    // from load_and_select('https://example.com/products', '.product-item');
    // ```
    //
    // Example 2: Join multiple pages
    // ```sql
    // select p.title, d.description
    // from load_and_select('url1', 'body') as p
    // join load_and_select('url2', 'body') as d
    // on true;
    // ```
    //
    // Example 3: Filter results
    // ```sql
    // select * from (
    //     select dom_first_text(dom, '.price') as price
    //     from load_and_select('url', '.item')
    // ) where cast(price as float) < 100;
    // ```
}
