package ai.platon.pulsar.persist.experimental;

import ai.platon.pulsar.common.HtmlIntegrity;
import ai.platon.pulsar.common.browser.BrowserType;
import ai.platon.pulsar.common.config.VolatileConfig;
import ai.platon.pulsar.persist.*;
import ai.platon.pulsar.persist.gora.generated.GHypeLink;
import ai.platon.pulsar.persist.metadata.FetchMode;
import ai.platon.pulsar.persist.metadata.OpenPageCategory;
import ai.platon.pulsar.persist.metadata.PageCategory;
import ai.platon.pulsar.persist.model.ActiveDOMStat;
import ai.platon.pulsar.persist.model.ActiveDOMStatus;
import ai.platon.pulsar.persist.model.PageModel;
import org.xml.sax.InputSource;

import java.io.ByteArrayInputStream;
import java.nio.ByteBuffer;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.util.Collection;
import java.util.List;
import java.util.Map;

public interface WebAsset {
  String getKey();
  String getLocation();
  int getId();
  ByteBuffer getSignature();
  ByteBuffer getContent();
  String getEncoding();
  long getContentLength();
  String getReversedUrl();
  Metadata getMetadata();
  String getBaseUrl();
  CrawlMarks getMarks();
  String getArgs();
  ZoneId getZoneId();
  String getBatchId();
  int getDistance();
  HtmlIntegrity getHtmlIntegrity();
  int getFetchPriority();
  Instant getCreateTime();
  int getFetchCount();
  CrawlStatus getCrawlStatus();
  Instant getFetchTime();
  Instant getPrevFetchTime();
  Instant getPrevCrawlTime1();
  Duration getFetchInterval();
  ProtocolStatus getProtocolStatus();
  ProtocolHeaders getHeaders();
  String getReprUrl();
  int getFetchRetries();
  Instant getModifiedTime();
  Instant getPrevModifiedTime();
  PageCategory getPageCategory();
  ByteArrayInputStream getContentAsInputStream();
  long getAveContentLength();
  long getPersistedContentLength();
  long getLastContentLength();
  String getContentType();
  ByteBuffer getPrevSignature();
  String getProxy();
  ActiveDOMStatus getActiveDOMStatus();
  Map<String, ActiveDOMStat> getActiveDOMStatTrace();
  String getPageTitle();
  String getContentTitle();
  String getPageText();
  String getContentText();
  int getContentTextLen();
  ParseStatus getParseStatus();
  Map<CharSequence, GHypeLink> getLiveLinks();
  String getUrl();
  Map<CharSequence, CharSequence> getVividLinks();
  List<CharSequence> getDeadLinks();
  List<CharSequence> getLinks();
  int getImpreciseLinkCount();
  Map<CharSequence, CharSequence> getInlinks();
  CharSequence getAnchor();
  int getAnchorOrder();
  Instant getContentPublishTime();
  Instant getPrevContentPublishTime();
  Instant getRefContentPublishTime();
  Instant getContentModifiedTime();
  Instant getPrevContentModifiedTime();
  Instant getPrevRefContentPublishTime();
  String getReferrer();
  Instant getPageModelUpdateTime();
  PageModel getPageModel();
  float getScore();
  float getContentScore();
  String getSortScore();
  PageCounters getPageCounters();
  String getHref();
  Variables getVariables();
  Object getVar(String name);
  VolatileConfig getConf();
  Duration getRetryDelay();
  int getMaxRetries();
  String getConfiguredUrl();
  int getFetchedLinkCount();
  FetchMode getFetchMode();
  BrowserType getLastBrowser();
  Instant getGenerateTime();
  OpenPageCategory getOpenPageCategory();
  String getEncodingOrDefault(String defaultValue);
  String getEncodingClues();
  ByteBuffer getTmpContent();
  ByteBuffer getPersistContent();
  byte[] getContentAsBytes();
  String getContentAsString();
  InputSource getContentAsSaxInputSource();
  String getPrevSignatureAsString();
  String getSignatureAsString();
  Collection<String> getSimpleLiveLinks();
  String[] getInlinkAnchors();
  float getCash();
}
