###
# 北京市经济和信息化委员会-经信动态-政务要闻
# http://jxj.beijing.gov.cn/jxdt/zwyw/
POST http://localhost:8182/x/e
Content-Type: text/plain

select
    dom_first_text(doc, '.container .title h1') as title,
    dom_first_text(doc, '#con_time, .container .pubdate') as publish_time,
    dom_first_text(doc, '.container .content') as content,
    dom_all_imgs(doc, '.container .content') as content_imgs,
    dom_uri(doc) as URI,
    *
from
    news_load_and_extract('http://jxj.beijing.gov.cn/jxdt/zwyw/202103/t20210312_2305500.html')

###
# 北京市经济和信息化委员会-经信动态-通知公告
# http://jxj.beijing.gov.cn/jxdt/tzgg/
POST http://localhost:8182/x/e
Content-Type: text/plain

select
    dom_first_text(doc, '#main .news_tit_ly') as title,
    dom_first_text(doc, '#main .newsly_ly') as publish_time,
    dom_first_text(doc, '#tex') as content,
    dom_all_imgs(doc, '#tex') as content_imgs,
    dom_uri(doc) as URI,
    *
from
    news_load_and_extract('http://gxt.jl.gov.cn/xxgk/zcwj/bwgz/202005/t20200518_7222440.html')

###
# 北京市经济和信息化委员会-政策·解读-政策文件-北京市政策
# http://jxj.beijing.gov.cn/zwgk/zcjd/
POST http://localhost:8182/x/e
Content-Type: text/plain

select
    dom_first_text(doc, '#main .news_tit_ly') as title,
    dom_first_text(doc, '#main .newsly_ly') as publish_time,
    dom_first_text(doc, '#tex') as content,
    dom_all_imgs(doc, '#tex') as content_imgs,
    dom_uri(doc) as URI,
    *
from
    news_load_and_extract('http://jxj.beijing.gov.cn/zwgk/zcjd/202101/t20210113_2218269.html')

###
# 北京市经济和信息化委员会-经信动态-行业动态
# http://jxj.beijing.gov.cn/jxdt/gzdt/
POST http://localhost:8182/x/e
Content-Type: text/plain

select
    dom_first_text(doc, '.container .title h1') as title,
    dom_first_text(doc, '#con_time, .container .pubdate') as publish_time,
    dom_first_text(doc, '.container .content') as content,
    dom_all_imgs(doc, '.container .content') as content_imgs,
    dom_uri(doc) as URI,
    *
from
    news_load_and_extract('http://jxj.beijing.gov.cn/jxdt/gzdt/202103/t20210319_2311446.html')

###
# 天津市工业和信息化委员会-最新信息-最新信息
# http://gyxxh.tj.gov.cn/ZWXX5652/TZGG644/2021n/
POST http://localhost:8182/x/e
Content-Type: text/plain

select
    dom_first_text(doc, '.main .qt-title') as title,
    dom_first_text(doc, '.main .p-title:containsOwn(发布时间)') as publish_time,
    dom_first_text(doc, '.main .xw-txt') as content,
    dom_all_imgs(doc, '.main .xw-txt') as content_imgs,
    dom_uri(doc) as URI,
    *
from
    news_load_and_extract('http://gyxxh.tj.gov.cn/ZWGK4147/zfxxgknew/fdzdgknrnew/qtfdgkxxnew/202105/t20210508_5445119.html')

###
# 天津市工业和信息化委员会-最新信息-工作动态
# http://gyxxh.tj.gov.cn/ZWXX5652/GXDT9285/
POST http://localhost:8182/x/e
Content-Type: text/plain

select
    dom_first_text(doc, '.containner .news_title') as title,
    dom_first_text(doc, '.containner .news_info span:containsOwn(发布时间)') as publish_time,
    dom_first_text(doc, '.containner .page_info') as content,
    dom_all_imgs(doc, '.containner .page_info') as content_imgs,
    dom_uri(doc) as URI,
    *
from
    news_load_and_extract('http://gyxxh.tj.gov.cn/ZWXX5652/GXDT9285/202105/t20210510_5446680.html')

###
# 天津市工业和信息化委员会-政务公开-通知公告
# http://gyxxh.tj.gov.cn/ZWXX5652/TZGG644/2021n/
POST http://localhost:8182/x/e
Content-Type: text/plain

select
    dom_first_text(doc, '.main .qt-title') as title,
    dom_first_text(doc, '.main .p-title:containsOwn(发布时间)') as publish_time,
    dom_first_text(doc, '.main .xw-txt') as content,
    dom_all_imgs(doc, '.main .xw-txt') as content_imgs,
    dom_uri(doc) as URI,
    *
from
    news_load_and_extract('http://gyxxh.tj.gov.cn/ZWGK4147/zfxxgknew/fdzdgknrnew/qtfdgkxxnew/202105/t20210508_5445119.html')

###
# 天津市工业和信息化委员会-政务公开-政策文件
# http://gyxxh.tj.gov.cn/ZWGK4147/ZCWJ6355/gjjwj/
POST http://localhost:8182/x/e
Content-Type: text/plain

select
    dom_first_text(doc, '.containner .news_title') as title,
    dom_first_text(doc, '.containner .news_info span:containsOwn(发布时间)') as publish_time,
    dom_first_text(doc, '.containner .page_info') as content,
    dom_all_imgs(doc, '.containner .page_info') as content_imgs,
    dom_uri(doc) as URI,
    *
from
    news_load_and_extract('http://gyxxh.tj.gov.cn/ZWGK4147/ZCWJ6355/gjjwj/202101/t20210107_5291332.html')
