name: 'Run Integration Tests'
description: 'Runs integration tests against a running application instance'

inputs:
  script_path:
    description: 'Path to the integration test script'
    required: false
    default: './bin/run-integration-test.sh'
  application_url:
    description: 'Application URL to test against'
    required: false
    default: 'http://localhost:8182'
  network_name:
    description: 'Docker network name'
    required: false
  container_name:
    description: 'Application container name'
    required: false
  timeout_seconds:
    description: 'Timeout for integration tests in seconds'
    required: false
    default: '600'

outputs:
  integration_status:
    description: 'Status of the integration tests (success, failed, skipped)'
    value: ${{ steps.run-tests.outputs.integration_status }}
  integration_exit_code:
    description: 'Exit code of the integration tests (if failed)'
    value: ${{ steps.run-tests.outputs.integration_exit_code }}
  integration_duration:
    description: 'Duration of the integration tests in seconds'
    value: ${{ steps.run-tests.outputs.integration_duration }}
  integration_time:
    description: 'Timestamp when integration tests completed'
    value: ${{ steps.run-tests.outputs.integration_time }}

runs:
  using: 'composite'
  steps:
    - name: Run Integration Tests
      id: run-tests
      shell: bash
      run: |
        echo "::group::🧪 Integration Tests"
        
        if [ -f "${{ inputs.script_path }}" ]; then
          echo "✅ Found integration test script"
          chmod +x ${{ inputs.script_path }}
        
          echo "🚀 Running integration tests..."
          echo "Application URL: ${{ inputs.application_url }}"
          echo "Network: ${{ inputs.network_name }}"
          echo "Container: ${{ inputs.container_name }}"
        
          start_time=$(date +%s)
          if timeout ${{ inputs.timeout_seconds }} ${{ inputs.script_path }}; then
            end_time=$(date +%s)
            duration=$((end_time - start_time))
            echo "✅ Integration tests passed (completed in ${duration}s)"
            echo "integration_status=success" >> $GITHUB_OUTPUT
            echo "integration_duration=${duration}" >> $GITHUB_OUTPUT
            echo "integration_time=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
          else
            EXIT_CODE=$?
            end_time=$(date +%s)
            duration=$((end_time - start_time))
            echo "❌ Integration tests failed with exit code: $EXIT_CODE (took ${duration}s)"
            echo "integration_status=failed" >> $GITHUB_OUTPUT
            echo "integration_exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
            echo "integration_duration=${duration}" >> $GITHUB_OUTPUT
            echo "integration_time=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
            exit 1
          fi
        else
          echo "⚠️ Integration test script not found: ${{ inputs.script_path }}"
          echo "Skipping integration tests..."
          echo "integration_status=skipped" >> $GITHUB_OUTPUT
        fi
        
        echo "::endgroup::"
