/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package fun.platonic.pulsar.persist;

import fun.platonic.pulsar.persist.gora.generated.GFieldGroup;

import java.util.Map;

public class FieldGroup {
    private GFieldGroup fieldGroup;

    private FieldGroup(GFieldGroup fieldGroup) {
        this.fieldGroup = fieldGroup;
    }

    public static FieldGroup newFieldGroup(long id, String name) {
        return newFieldGroup(id, name, 0);
    }

    public static FieldGroup newFieldGroup(long id, String name, long parentId) {
        GFieldGroup fieldGroup = GFieldGroup.newBuilder().build();
        fieldGroup.setId(id);
        fieldGroup.setParentId(parentId);
        fieldGroup.setName(name);
        return FieldGroup.box(fieldGroup);
    }

    public static FieldGroup box(GFieldGroup fieldGroup) {
        return new FieldGroup(fieldGroup);
    }

    public GFieldGroup unbox() {
        return fieldGroup;
    }

    public long getId() {
        return fieldGroup.getId();
    }

    public void setId(long id) {
        fieldGroup.setId(id);
    }

    public long getParentId() {
        return fieldGroup.getParentId();
    }

    public void setParentId(long id) {
        fieldGroup.setParentId(id);
    }

    public String getName() {
        return fieldGroup.getName().toString();
    }

    public void setName(String name) {
        fieldGroup.setName(name);
    }

    public Map<CharSequence, CharSequence> getFields() {
        return fieldGroup.getFields();
    }

    public void setFields(Map<CharSequence, CharSequence> fields) {
        fieldGroup.setFields(fields);
    }

    @Override
    public String toString() {
        return new FieldGroupFormatter(this).format();
    }
}
