= The Pulsar log format explained
Vincent Zhang <ivincent.zhang@gmail.com>
3.0, Sep 24, 2022: The Pulsar log format explained
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Here are 5 example logs which report the status of loaded pages:

[source,composer log,options="nowrap"]
----
2022-09-24 11:46:26.045  INFO [-worker-14] a.p.p.c.c.L.Task - 3313. 💯 ⚡ U for N got 200 580.92 KiB in 1m14.277s, fc:1 | 75/284/96/277/6554 | 106.32.12.75 | 3xBpaR2 | https://www.walmart.com/ip/Restored-iPhone-7-32GB-Black-T-Mobile-Refurbished/329207863 -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
2022-09-24 11:46:09.190  INFO [-worker-32] a.p.p.c.c.L.Task - 3738. 💯 💿 U  got 200 452.91 KiB in 55.286s, last fetched 9h32m50s ago, fc:1 | 49/171/82/238/6172 | 121.205.220.179 | https://www.walmart.com/ip/Boost-Mobile-Apple-iPhone-SE-2-Cell-Phone-Black-64GB-Prepaid-Smartphone/490934488 -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
2022-09-24 11:46:28.567  INFO [-worker-17] a.p.p.c.c.L.Task - 2269. 💯 🔃 U for SC got 200 565.07 KiB <- 543.41 KiB in 1m22.767s, last fetched 16m58s ago, fc:6 | 58/230/98/295/6272 | 27.158.125.76 | 9uwu602 | https://www.walmart.com/ip/Straight-Talk-Apple-iPhone-11-64GB-Purple-Prepaid-Smartphone/356345388?variantFieldId=actual_color -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
2022-09-24 11:47:18.390  INFO [r-worker-8] a.p.p.c.c.L.Task - 3732. 💔 ⚡ U for N got 1601 0 <- 0 in 32.201s, fc:1/1 Retry(1601) rsp: CRAWL, rrs: EMPTY_0B | 2zYxg52 | https://www.walmart.com/ip/Apple-iPhone-7-256GB-Jet-Black-AT-T-Locked-Smartphone-Grade-B-Used/182353175?variantFieldId=actual_color -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
2022-09-24 11:47:13.860  INFO [-worker-60] a.p.p.c.c.L.Task - 2828. 🗙 🗙 U for SC got 200 0 <- 348.31 KiB <- 684.75 KiB in 0s, last fetched 18m55s ago, fc:2 | 34/130/52/181/5747 | 60.184.124.232 | 11zTa0r2 | https://www.walmart.com/ip/Walmart-Family-Mobile-Apple-iPhone-11-64GB-Black-Prepaid-Smartphone/209201965?athbdg=L1200 -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
----

The following example log reports a retrying page:

[source,composer log,options="nowrap"]
----
2022-09-24 11:46:12.167  INFO [-worker-62] a.p.p.c.i.S.Task - 3744. 🤺 Trying 2th 10s later | U  got 1601 0 <- 0 in 1m0.612s, last fetched 10s ago, fc:1/1 Retry(1601) rsp: CRAWL | https://www.walmart.com/ip/iPhone-7-128GB-Silver-Boost-Mobile-Used-Grade-B/662547852
----

This document explains each field in the logs.

[source,composer log,options="nowrap"]
----
Date       Time          LogLevel  ThreadName   LogName
2022-09-24 11:46:12.167  INFO      [-worker-62] a.p.p.c.i.S.Task -
2022-09-24 11:46:09.190  INFO      [-worker-32] a.p.p.c.c.L.Task -
----

Continued:
[source,composer log,options="nowrap"]
----
PageId    TaskStatus PageStatus  PageCategory      FetchReason     FetchCode PageSize                           FetchTime
3313.     💯         ⚡            U             for N           got 200         580.92 KiB                     in 1m14.277s
3738.     💯         💿           U                             got 200          452.91 KiB                    in 55.286s
2269.     💯         🔃           U             for SC          got 200          565.07 KiB <- 543.41 KiB      in 1m22.767s
3732.     💔         ⚡            U             for N           got 1601         0 <- 0 in 32.201s
2828.     🗙         🗙            U            for SC           got 200         0 <- 348.31 KiB <- 684.75 KiB in 0s
----

PageId is the id of the WebPage object and is unique process-wide.

TaskStatus is a unicode symbol, can be one of the following:

    💯 - Task is success
    💔 - Task is failed
    🗙 - Task is canceled

and for retrying tasks, the symbol is:

    🤺 - Task is retrying

PageStatus is a unicode symbol, can be one of the following:

    ⚡ - Page is first fetched from the Internet
    💿 - Page is loaded from hard disk
    🔃 - Page is updated from the Internet
    🗙 - Page is canceled and remains unchanged

FetchReason indicates why the page was fetched. The reason can be one of the following:

- The page was never fetched
- The page has expired since the last fetch
- The -refresh option is applied, so the page should be refreshed
- The page is scheduled to fetch
- Last fetch failed, retrying
- Last fetched page has no content
- Last fetched page content was too small
- Required fields missed in the last fetched page content
- The page was temporary moved

FetchReason contains one or two characters, it's defined as the following:

    symbols[DO_NOT_FETCH] = ""
    symbols[NEW_PAGE] = "N"
    symbols[REFRESH] = "RR"
    symbols[EXPIRED] = "EX"
    symbols[SCHEDULED] = "SD"
    symbols[RETRY] = "RT"
    symbols[NO_CONTENT] = "NC"
    symbols[SMALL_CONTENT] = "SC"
    symbols[MISS_FIELD] = "MF"
    symbols[TEMP_MOVED] = "TM"
    symbols[UNKNOWN] = "U"

FetchCode is a number, describes the fetch phrase status, inherited from the standard HTTP error code, usually be one of:

    200 - success
    1601 - retry

All codes are defined in link:pulsar-persist/src/main/java/ai/platon/pulsar/persist/metadata/ProtocolStatusCodes.java[ProtocolStatusCodes].

Continued:
[source,composer log,options="nowrap"]
----
PrevFetchTime               FetchCount        FetchFailure                           DOMStatistic         ProxyIP           PrivacyContext
                            fc:1 |                                                   75/284/96/277/6554 | 106.32.12.75    | 3xBpaR2
last fetched 9h32m50s ago,  fc:1 |                                                   49/171/82/238/6172 | 121.205.220.179
last fetched 16m58s ago,    fc:6 |                                                   58/230/98/295/6272 | 27.158.125.76   | 9uwu602
                            fc:1/1            Retry(1601) rsp: CRAWL, rrs: EMPTY_0B                                       | 2zYxg52
last fetched 18m55s ago,    fc:2 |                                                   34/130/52/181/5747 | 60.184.124.232  | 11zTa0r2
----

PrevFetchTime is the time of the previous fetch.

FetchCount is the count of all fetch executions, excluding cancelled fetches.

FetchFailure is the failure information of the most recent fetch execution, and it is empty if it succeeded.

DOMStatistic contains simple statistics on the HTML document, the statistics are calculated in a real browser using javascript.

    58/230/98/295/6272 (i/a/nm/st/h)

where

    i:  anchor count
    a:  image count
    nm: number count
    st: small text count
    h:  document height in pexels

Check DOMStatistic to see if the page was fetched correctly, for example, a fully loaded page is usually above 5,000 pixels, and anything below that means the page may need to be re-fetched.

For the other fields, such as ProxyIP, PrivacyContext, there is no need to explain.

Continued:
[source,composer log,options="nowrap"]
----
URL
https://www.walmart.com/ip/329207863 -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
https://www.walmart.com/ip/490934488 -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
https://www.walmart.com/ip/356345388 -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
https://www.walmart.com/ip/182353175 -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
https://www.walmart.com/ip/209201965 -expires PT24H -ignoreFailure -itemExpires PT1M -outLinkSelector a[href~=/ip/] -parse -requireSize 300000
----

URL is the url to fetch. The url can follow load arguments, or load options, check link:docs/concepts.adoc#_load_options[Load Options] for details.
