= X-SQL
Vincent Zhang <ivincent.zhang@gmail.com>
3.0, July 29, 2022: Frequently Asked Questions
:toc:
:icons: font

We developed X-SQL to query the Web directly and convert webpages into tables and charts.

X-SQL is build on h2 database, so it's compatible with h2 and the SQL dialect is h2.

A typical X-SQL is shown below:

[source,sql]
----
select
  dom_base_uri(dom) as url,
  dom_first_text(dom, '#productTitle') as title,
  str_substring_after(dom_first_href(dom, '#wayfinding-breadcrumbs_container ul li:last-child a'), '&node=') as category,
  dom_first_slim_html(dom, '#bylineInfo') as brand,
  dom_all_slim_htmls(dom, '#imageBlock img') as gallery,
  dom_first_slim_html(dom, '#landingImage, #imgTagWrapperId img, #imageBlock img:expr(width > 400)') as img,
  dom_first_text(dom, '#price tr td:contains(List Price) ~ td') as listprice,
  dom_first_text(dom, '#price tr td:matches(^Price) ~ td') as price,
  str_first_float(dom_first_text(dom, '#reviewsMedley .AverageCustomerReviews span:contains(out of)'), 0.0) as score
from load_and_select('https://www.amazon.com/dp/B09V3KXJPB -i 1d -njr 3', 'body');
----

Pulsar extends H2 database mainly by registering UDFs.

Every X-SQL function has a namespace, for example:

    dom_base_uri() -> dom
    str_substring_after() -> str

In the above examples, `dom` and `str` are namespaces. If a  X-SQL function is declared as `hasShortcut`, the namespace can be ignored.

X-SQL functions are case-insensitive, and all underscores (`_`) are ignored.

The following X-SQL functions are all the same:

    DOM_LOAD_AND_SELECT(url, 'body');
    dom_loadAndSelect(url, 'body');
    Dom_Load_And_Select(url, 'body');
    dom_load_and_select(url, 'body');
    dOm_____lo_AdaNd_S___elEct_____(url, 'body');

Since LOAD_AND_SELECT is declared as `hasShortcut`, so the namespace can be ignored, the following functions are still the same:

    LOAD_AND_SELECT(url, 'body');
    loadAndSelect(url, 'body');
    Load_And_Select(url, 'body');
    load_and_select(url, 'body');
    _____lo_AdaNd_S___elEct_____(url, 'body');

## Table Functions

Each table function returns a ResultSet and can appear in the `from` clause.

### LOAD_AND_SELECT

    LOAD_AND_SELECT(url [cssSelector [, offset [, limit]]])

Load a page and select elements, returns a ResultSet. The returned ResultSet has two columns: `DOM` and `DOC`, the types of these two columns are `ValueDom`.

Example:

[source,sql]
----
select
    dom_base_uri(dom)
from
    load_and_select('https://www.amazon.com/dp/B09V3KXJPB', 'body', 1, 10)
----

## DOM Functions

DOM functions are designed to work with DOM. Every DOM function accepts a `ValueDom` parameter, which is a wrapper of a Jsoup Element.

Most important DOM functions are defined in link:../pulsar-ql/src/main/kotlin/ai/platon/pulsar/ql/h2/udfs/DomFunctions.kt[DomFunctions], link:../pulsar-ql/src/main/kotlin/ai/platon/pulsar/ql/h2/udfs/DomSelectFunctions.kt[DomSelectFunctions].

All DOM functions are in the namespace `DOM`.

### DOM_BASE_URI

    DOM_BASE_URI(dom)

Returns the URI of the HTML document.

Example:

[source,sql]
----
select dom_base_uri(dom) from load_and_select('https://www.amazon.com/dp/B09V3KXJPB', 'body')
----

### DOM_FIRST_TEXT

    DOM_FIRST_TEXT(dom, cssSelector)

Returns the text content of the first element selected by `cssSelector` inside `dom`, it's similar to the javascript code below:

    dom.querySelector(cssSelector).textContent

Example:

[source,sql]
----
select
    dom_first_text(dom, '#productName') as Name,
    dom_first_text(dom, '#price') as Price,
    dom_first_text(dom, '#star') as StarNum
from
    load_and_select('https://www.example.com/zgbs/appliances', 'ul.item-collection li.item')
----

## String Functions

All string functions are generated from org.apache.commons.lang3.StringUtils automatically. You can find the UDF definition in link:../pulsar-ql/src/main/kotlin/ai/platon/pulsar/ql/h2/udfs/StringFunctions.kt[StringFunctions].

All string functions are in the namespace `STR`.

### STR_SUBSTRING_AFTER

    STR_SUBSTRING_AFTER(str, separator)

Gets the substring after the first occurrence of a separator.

Example:

[source,sql]
----
select
    str_substring_after(dom_first_text(dom, '#price'), '$') as Price
from
    load_and_select('https://www.amazon.com/dp/B09V3KXJPB', 'body');
----
