= X-SQL
Vincent Zhang <ivincent.zhang@gmail.com>
3.0, July 29, 2022: Frequently Asked Questions
:toc:
:icons: font

我们开发了 X-SQL 来直接查询网页，并将网页转换成表格和图表。

X-SQL 建立在 H2 数据库上，所以它与 H2 兼容，SQL 方言是 H2。

一个典型的 X-SQL 如下所示。

[source,sql]
----
select
  dom_base_uri(dom) as url,
  dom_first_text(dom, '#productTitle') as title,
  str_substring_after(dom_first_href(dom, '#wayfinding-breadcrumbs_container ul li:last-child a'), '&node=') as category,
  dom_first_slim_html(dom, '#bylineInfo') as brand,
  dom_all_slim_htmls(dom, '#imageBlock img') as gallery,
  dom_first_slim_html(dom, '#landingImage, #imgTagWrapperId img, #imageBlock img:expr(width > 400)') as img,
  dom_first_text(dom, '#price tr td:contains(List Price) ~ td') as listprice,
  dom_first_text(dom, '#price tr td:matches(^Price) ~ td') as price,
  str_first_float(dom_first_text(dom, '#reviewsMedley .AverageCustomerReviews span:contains(out of)'), 0.0) as score
from load_and_select('https://www.amazon.com/dp/B09V3KXJPB -i 1d -njr 3', 'body');
----

Pulsar 主要通过注册 UDF 来扩展 H2 数据库，但也做了其他扩展。

每个 X-SQL 函数都有一个命名空间，例如:

    dom_base_uri() -> dom
    str_substring_after() -> str

在上面的例子中，`dom` 和 `str` 是命名空间。如果将 X-SQL 函数声明为 `hasShortcut`, 则可以忽略该命名空间。

X-SQL 函数不区分大小写，所有下划线(`_`)都会被忽略。

以下 X-SQL 函数都是相同的:

    DOM_LOAD_AND_SELECT(url, 'body');
    dom_loadAndSelect(url, 'body');
    Dom_Load_And_Select(url, 'body');
    dom_load_and_select(url, 'body');
    dOm_____lo_AdaNd_S___elEct_____(url, 'body');

由于 LOAD_AND_SELECT 被声明为 `hasShortcut`，因此可以忽略命名空间，以下函数仍然相同：

    LOAD_AND_SELECT(url, 'body');
    loadAndSelect(url, 'body');
    Load_And_Select(url, 'body');
    load_and_select(url, 'body');
    _____lo_AdaNd_S___elEct_____(url, 'body');

## Table Functions

每个 table function 都返回一个 ResultSet，并且可以出现在 `from` 子句中。

### LOAD_AND_SELECT

    LOAD_AND_SELECT(url [cssSelector [, offset [, limit]]])

加载一个页面并选择元素，返回一个 ResultSet。返回的结果集有两列：`DOM`和`DOC`，这两列的类型是 `ValueDom`。

示例：

[source,sql]
----
select
    dom_base_uri(dom)
from
    load_and_select('https://www.amazon.com/dp/B09V3KXJPB', 'body', 1, 10)
----

## DOM Functions

DOM 函数被设计为与 DOM 一起工作。每个DOM函数都接受一个 `ValueDom` 参数，它是一个 Jsoup Element 的包装。

最重要的 DOM 函数定义在下面几个文件中：link:../pulsar-ql/src/main/kotlin/ai/platon/pulsar/ql/h2/udfs/DomFunctions.kt[DomFunctions], link:../pulsar-ql/src/main/kotlin/ai/platon/pulsar/ql/h2/udfs/DomSelectFunctions.kt[DomSelectFunctions].

所有的字符串函数都在命名空间 `DOM` 中。

### DOM_BASE_URI

    DOM_BASE_URI(dom)

返回 HTML 文档的 URI。

示例：

[source,sql]
----
select dom_base_uri(dom) from load_and_select('https://www.amazon.com/dp/B09V3KXJPB', 'body')
----

### DOM_FIRST_TEXT

    DOM_FIRST_TEXT(dom, cssSelector)

返回由`cssSelector`在`dom`内选择的第一个元素的文本内容，它类似于下面的javascript代码。

    dom.querySelector(cssSelector).textContent

示例：

[source,sql]
----
select
    dom_first_text(dom, '#productName') as Name,
    dom_first_text(dom, '#price') as Price,
    dom_first_text(dom, '#star') as StarNum
from
    load_and_select('https://www.example.com/zgbs/appliances', 'ul.item-collection li.item')
----

## String Functions

所有的字符串函数都是通过程序从 org.apache.commons.lang3.StringUtils 自动转换而来。你可以在下述文件中找到 UDF 定义：link:../pulsar-ql/src/main/kotlin/ai/platon/pulsar/ql/h2/udfs/StringFunctions.kt[StringFunctions].

所有的字符串函数都在命名空间 `STR` 中。

### STR_SUBSTRING_AFTER

    STR_SUBSTRING_AFTER(str, separator)

获取第一次出现的分隔符后的子串。

示例：

[source,sql]
----
select
    str_substring_after(dom_first_text(dom, '#price'), '$') as Price
from
    load_and_select('https://www.amazon.com/dp/B09V3KXJPB', 'body');
----
