package com.github.kklisura.cdt.protocol.v2023.types.page;

/*-
 * #%L
 * cdt-java-client
 * %%
 * Copyright (C) 2018 - 2023 Kenan Klisura
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import com.fasterxml.jackson.annotation.JsonProperty;

/** List of not restored reasons for back-forward cache. */
public enum BackForwardCacheNotRestoredReason {
  @JsonProperty("NotPrimaryMainFrame")
  NOT_PRIMARY_MAIN_FRAME,
  @JsonProperty("BackForwardCacheDisabled")
  BACK_FORWARD_CACHE_DISABLED,
  @JsonProperty("RelatedActiveContentsExist")
  RELATED_ACTIVE_CONTENTS_EXIST,
  @JsonProperty("HTTPStatusNotOK")
  HTTP_STATUS_NOT_OK,
  @JsonProperty("SchemeNotHTTPOrHTTPS")
  SCHEME_NOT_HTTP_OR_HTTPS,
  @JsonProperty("Loading")
  LOADING,
  @JsonProperty("WasGrantedMediaAccess")
  WAS_GRANTED_MEDIA_ACCESS,
  @JsonProperty("DisableForRenderFrameHostCalled")
  DISABLE_FOR_RENDER_FRAME_HOST_CALLED,
  @JsonProperty("DomainNotAllowed")
  DOMAIN_NOT_ALLOWED,
  @JsonProperty("HTTPMethodNotGET")
  HTTP_METHOD_NOT_GET,
  @JsonProperty("SubframeIsNavigating")
  SUBFRAME_IS_NAVIGATING,
  @JsonProperty("Timeout")
  TIMEOUT,
  @JsonProperty("CacheLimit")
  CACHE_LIMIT,
  @JsonProperty("JavaScriptExecution")
  JAVA_SCRIPT_EXECUTION,
  @JsonProperty("RendererProcessKilled")
  RENDERER_PROCESS_KILLED,
  @JsonProperty("RendererProcessCrashed")
  RENDERER_PROCESS_CRASHED,
  @JsonProperty("SchedulerTrackedFeatureUsed")
  SCHEDULER_TRACKED_FEATURE_USED,
  @JsonProperty("ConflictingBrowsingInstance")
  CONFLICTING_BROWSING_INSTANCE,
  @JsonProperty("CacheFlushed")
  CACHE_FLUSHED,
  @JsonProperty("ServiceWorkerVersionActivation")
  SERVICE_WORKER_VERSION_ACTIVATION,
  @JsonProperty("SessionRestored")
  SESSION_RESTORED,
  @JsonProperty("ServiceWorkerPostMessage")
  SERVICE_WORKER_POST_MESSAGE,
  @JsonProperty("EnteredBackForwardCacheBeforeServiceWorkerHostAdded")
  ENTERED_BACK_FORWARD_CACHE_BEFORE_SERVICE_WORKER_HOST_ADDED,
  @JsonProperty("RenderFrameHostReused_SameSite")
  RENDER_FRAME_HOST_REUSED_SAME_SITE,
  @JsonProperty("RenderFrameHostReused_CrossSite")
  RENDER_FRAME_HOST_REUSED_CROSS_SITE,
  @JsonProperty("ServiceWorkerClaim")
  SERVICE_WORKER_CLAIM,
  @JsonProperty("IgnoreEventAndEvict")
  IGNORE_EVENT_AND_EVICT,
  @JsonProperty("HaveInnerContents")
  HAVE_INNER_CONTENTS,
  @JsonProperty("TimeoutPuttingInCache")
  TIMEOUT_PUTTING_IN_CACHE,
  @JsonProperty("BackForwardCacheDisabledByLowMemory")
  BACK_FORWARD_CACHE_DISABLED_BY_LOW_MEMORY,
  @JsonProperty("BackForwardCacheDisabledByCommandLine")
  BACK_FORWARD_CACHE_DISABLED_BY_COMMAND_LINE,
  @JsonProperty("NetworkRequestDatapipeDrainedAsBytesConsumer")
  NETWORK_REQUEST_DATAPIPE_DRAINED_AS_BYTES_CONSUMER,
  @JsonProperty("NetworkRequestRedirected")
  NETWORK_REQUEST_REDIRECTED,
  @JsonProperty("NetworkRequestTimeout")
  NETWORK_REQUEST_TIMEOUT,
  @JsonProperty("NetworkExceedsBufferLimit")
  NETWORK_EXCEEDS_BUFFER_LIMIT,
  @JsonProperty("NavigationCancelledWhileRestoring")
  NAVIGATION_CANCELLED_WHILE_RESTORING,
  @JsonProperty("NotMostRecentNavigationEntry")
  NOT_MOST_RECENT_NAVIGATION_ENTRY,
  @JsonProperty("BackForwardCacheDisabledForPrerender")
  BACK_FORWARD_CACHE_DISABLED_FOR_PRERENDER,
  @JsonProperty("UserAgentOverrideDiffers")
  USER_AGENT_OVERRIDE_DIFFERS,
  @JsonProperty("ForegroundCacheLimit")
  FOREGROUND_CACHE_LIMIT,
  @JsonProperty("BrowsingInstanceNotSwapped")
  BROWSING_INSTANCE_NOT_SWAPPED,
  @JsonProperty("BackForwardCacheDisabledForDelegate")
  BACK_FORWARD_CACHE_DISABLED_FOR_DELEGATE,
  @JsonProperty("UnloadHandlerExistsInMainFrame")
  UNLOAD_HANDLER_EXISTS_IN_MAIN_FRAME,
  @JsonProperty("UnloadHandlerExistsInSubFrame")
  UNLOAD_HANDLER_EXISTS_IN_SUB_FRAME,
  @JsonProperty("ServiceWorkerUnregistration")
  SERVICE_WORKER_UNREGISTRATION,
  @JsonProperty("CacheControlNoStore")
  CACHE_CONTROL_NO_STORE,
  @JsonProperty("CacheControlNoStoreCookieModified")
  CACHE_CONTROL_NO_STORE_COOKIE_MODIFIED,
  @JsonProperty("CacheControlNoStoreHTTPOnlyCookieModified")
  CACHE_CONTROL_NO_STORE_HTTP_ONLY_COOKIE_MODIFIED,
  @JsonProperty("NoResponseHead")
  NO_RESPONSE_HEAD,
  @JsonProperty("Unknown")
  UNKNOWN,
  @JsonProperty("ActivationNavigationsDisallowedForBug1234857")
  ACTIVATION_NAVIGATIONS_DISALLOWED_FOR_BUG_1234857,
  @JsonProperty("ErrorDocument")
  ERROR_DOCUMENT,
  @JsonProperty("FencedFramesEmbedder")
  FENCED_FRAMES_EMBEDDER,
  @JsonProperty("CookieDisabled")
  COOKIE_DISABLED,
  @JsonProperty("HTTPAuthRequired")
  HTTP_AUTH_REQUIRED,
  @JsonProperty("CookieFlushed")
  COOKIE_FLUSHED,
  @JsonProperty("WebSocket")
  WEB_SOCKET,
  @JsonProperty("WebTransport")
  WEB_TRANSPORT,
  @JsonProperty("WebRTC")
  WEB_RTC,
  @JsonProperty("MainResourceHasCacheControlNoStore")
  MAIN_RESOURCE_HAS_CACHE_CONTROL_NO_STORE,
  @JsonProperty("MainResourceHasCacheControlNoCache")
  MAIN_RESOURCE_HAS_CACHE_CONTROL_NO_CACHE,
  @JsonProperty("SubresourceHasCacheControlNoStore")
  SUBRESOURCE_HAS_CACHE_CONTROL_NO_STORE,
  @JsonProperty("SubresourceHasCacheControlNoCache")
  SUBRESOURCE_HAS_CACHE_CONTROL_NO_CACHE,
  @JsonProperty("ContainsPlugins")
  CONTAINS_PLUGINS,
  @JsonProperty("DocumentLoaded")
  DOCUMENT_LOADED,
  @JsonProperty("DedicatedWorkerOrWorklet")
  DEDICATED_WORKER_OR_WORKLET,
  @JsonProperty("OutstandingNetworkRequestOthers")
  OUTSTANDING_NETWORK_REQUEST_OTHERS,
  @JsonProperty("RequestedMIDIPermission")
  REQUESTED_MIDI_PERMISSION,
  @JsonProperty("RequestedAudioCapturePermission")
  REQUESTED_AUDIO_CAPTURE_PERMISSION,
  @JsonProperty("RequestedVideoCapturePermission")
  REQUESTED_VIDEO_CAPTURE_PERMISSION,
  @JsonProperty("RequestedBackForwardCacheBlockedSensors")
  REQUESTED_BACK_FORWARD_CACHE_BLOCKED_SENSORS,
  @JsonProperty("RequestedBackgroundWorkPermission")
  REQUESTED_BACKGROUND_WORK_PERMISSION,
  @JsonProperty("BroadcastChannel")
  BROADCAST_CHANNEL,
  @JsonProperty("WebXR")
  WEB_XR,
  @JsonProperty("SharedWorker")
  SHARED_WORKER,
  @JsonProperty("WebLocks")
  WEB_LOCKS,
  @JsonProperty("WebHID")
  WEB_HID,
  @JsonProperty("WebShare")
  WEB_SHARE,
  @JsonProperty("RequestedStorageAccessGrant")
  REQUESTED_STORAGE_ACCESS_GRANT,
  @JsonProperty("WebNfc")
  WEB_NFC,
  @JsonProperty("OutstandingNetworkRequestFetch")
  OUTSTANDING_NETWORK_REQUEST_FETCH,
  @JsonProperty("OutstandingNetworkRequestXHR")
  OUTSTANDING_NETWORK_REQUEST_XHR,
  @JsonProperty("AppBanner")
  APP_BANNER,
  @JsonProperty("Printing")
  PRINTING,
  @JsonProperty("WebDatabase")
  WEB_DATABASE,
  @JsonProperty("PictureInPicture")
  PICTURE_IN_PICTURE,
  @JsonProperty("Portal")
  PORTAL,
  @JsonProperty("SpeechRecognizer")
  SPEECH_RECOGNIZER,
  @JsonProperty("IdleManager")
  IDLE_MANAGER,
  @JsonProperty("PaymentManager")
  PAYMENT_MANAGER,
  @JsonProperty("SpeechSynthesis")
  SPEECH_SYNTHESIS,
  @JsonProperty("KeyboardLock")
  KEYBOARD_LOCK,
  @JsonProperty("WebOTPService")
  WEB_OTP_SERVICE,
  @JsonProperty("OutstandingNetworkRequestDirectSocket")
  OUTSTANDING_NETWORK_REQUEST_DIRECT_SOCKET,
  @JsonProperty("InjectedJavascript")
  INJECTED_JAVASCRIPT,
  @JsonProperty("InjectedStyleSheet")
  INJECTED_STYLE_SHEET,
  @JsonProperty("KeepaliveRequest")
  KEEPALIVE_REQUEST,
  @JsonProperty("IndexedDBEvent")
  INDEXED_DB_EVENT,
  @JsonProperty("Dummy")
  DUMMY,
  @JsonProperty("JsNetworkRequestReceivedCacheControlNoStoreResource")
  JS_NETWORK_REQUEST_RECEIVED_CACHE_CONTROL_NO_STORE_RESOURCE,
  @JsonProperty("WebRTCSticky")
  WEB_RTC_STICKY,
  @JsonProperty("WebTransportSticky")
  WEB_TRANSPORT_STICKY,
  @JsonProperty("WebSocketSticky")
  WEB_SOCKET_STICKY,
  @JsonProperty("ContentSecurityHandler")
  CONTENT_SECURITY_HANDLER,
  @JsonProperty("ContentWebAuthenticationAPI")
  CONTENT_WEB_AUTHENTICATION_API,
  @JsonProperty("ContentFileChooser")
  CONTENT_FILE_CHOOSER,
  @JsonProperty("ContentSerial")
  CONTENT_SERIAL,
  @JsonProperty("ContentFileSystemAccess")
  CONTENT_FILE_SYSTEM_ACCESS,
  @JsonProperty("ContentMediaDevicesDispatcherHost")
  CONTENT_MEDIA_DEVICES_DISPATCHER_HOST,
  @JsonProperty("ContentWebBluetooth")
  CONTENT_WEB_BLUETOOTH,
  @JsonProperty("ContentWebUSB")
  CONTENT_WEB_USB,
  @JsonProperty("ContentMediaSessionService")
  CONTENT_MEDIA_SESSION_SERVICE,
  @JsonProperty("ContentScreenReader")
  CONTENT_SCREEN_READER,
  @JsonProperty("EmbedderPopupBlockerTabHelper")
  EMBEDDER_POPUP_BLOCKER_TAB_HELPER,
  @JsonProperty("EmbedderSafeBrowsingTriggeredPopupBlocker")
  EMBEDDER_SAFE_BROWSING_TRIGGERED_POPUP_BLOCKER,
  @JsonProperty("EmbedderSafeBrowsingThreatDetails")
  EMBEDDER_SAFE_BROWSING_THREAT_DETAILS,
  @JsonProperty("EmbedderAppBannerManager")
  EMBEDDER_APP_BANNER_MANAGER,
  @JsonProperty("EmbedderDomDistillerViewerSource")
  EMBEDDER_DOM_DISTILLER_VIEWER_SOURCE,
  @JsonProperty("EmbedderDomDistillerSelfDeletingRequestDelegate")
  EMBEDDER_DOM_DISTILLER_SELF_DELETING_REQUEST_DELEGATE,
  @JsonProperty("EmbedderOomInterventionTabHelper")
  EMBEDDER_OOM_INTERVENTION_TAB_HELPER,
  @JsonProperty("EmbedderOfflinePage")
  EMBEDDER_OFFLINE_PAGE,
  @JsonProperty("EmbedderChromePasswordManagerClientBindCredentialManager")
  EMBEDDER_CHROME_PASSWORD_MANAGER_CLIENT_BIND_CREDENTIAL_MANAGER,
  @JsonProperty("EmbedderPermissionRequestManager")
  EMBEDDER_PERMISSION_REQUEST_MANAGER,
  @JsonProperty("EmbedderModalDialog")
  EMBEDDER_MODAL_DIALOG,
  @JsonProperty("EmbedderExtensions")
  EMBEDDER_EXTENSIONS,
  @JsonProperty("EmbedderExtensionMessaging")
  EMBEDDER_EXTENSION_MESSAGING,
  @JsonProperty("EmbedderExtensionMessagingForOpenPort")
  EMBEDDER_EXTENSION_MESSAGING_FOR_OPEN_PORT,
  @JsonProperty("EmbedderExtensionSentMessageToCachedFrame")
  EMBEDDER_EXTENSION_SENT_MESSAGE_TO_CACHED_FRAME
}
