name: Release Test

on:
  push:
    branches:
      - disabled-master
    tags:
      - 'disabled-v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test Sonatype login via API
        run: |
          curl -u "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" \
          -X GET "https://oss.sonatype.org/service/local/status"

      - name: Check if GPG is working
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Cache Maven wrapper
        uses: actions/cache@v3
        with:
          path: .mvn/wrapper
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/maven-wrapper.properties') }}

      - name: Deploy single JAR to Sonatype OSSRH
        if: success()
        run: |
          ./mvnw --batch-mode -pl pulsar-common -am package -DskipTests
          jar_file=$(find pulsar-common/target -name 'pulsar-common-*.jar' | head -n 1)
          ./mvnw --batch-mode deploy:deploy-file -P deploy,release -DskipTests \
            -Dfile="$jar_file" \
            -DpomFile=pulsar-common/pom.xml \
            -DrepositoryId=ossrh \
            -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2 \
            -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
