name: Release Test

on:
  push:
    branches:
      - master
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test Sonatype login via API
        run: |
          curl -u "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" \
          -X GET "https://oss.sonatype.org/service/local/status"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: ossrh
          settings-path: ${{ github.workspace }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Extract version from tag
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven build and deploy to local repo
        run: |
          chmod +x ./mvnw
          ./mvnw clean install -DskipTests -Pplaton-release -Pplaton-deploy

      - name: Deploy to Sonatype OSSRH
        if: success()
        run: |
          ./mvnw deploy -Pplaton-release -Pplaton-deploy -DskipTests -B \
            -Dgpg.passphrase="${GPG_PASSPHRASE}" \
            -s $GITHUB_WORKSPACE/settings.xml

        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
